Imported Upstream version 4.3.2.467

diff --git a/mono/tests/Makefile.in b/mono/tests/Makefile.in
--- a/mono/tests/Makefile.in
+++ b/mono/tests/Makefile.in
@@ -237,8 +237,6 @@ AUTOMAKE = @AUTOMAKE@
 AWK = @AWK@
 BOEHM_DEFINES = @BOEHM_DEFINES@
 BUILD_EXEEXT = @BUILD_EXEEXT@
-BUILD_GLIB_CFLAGS = @BUILD_GLIB_CFLAGS@
-BUILD_GLIB_LIBS = @BUILD_GLIB_LIBS@
 CC = @CC@
 CCAS = @CCAS@
 CCASDEPMODE = @CCASDEPMODE@
@@ -254,9 +252,9 @@ CXXCPP = @CXXCPP@
 CXXDEPMODE = @CXXDEPMODE@
 CXXFLAGS = @CXXFLAGS@
 CYGPATH_W = @CYGPATH_W@
+DEFAULT_PROFILE = @DEFAULT_PROFILE@
 DEFS = @DEFS@
 DEPDIR = @DEPDIR@
-DISABLE_SHARED_HANDLES = @DISABLE_SHARED_HANDLES@
 DLLTOOL = @DLLTOOL@
 DOLT_BASH = @DOLT_BASH@
 DSYMUTIL = @DSYMUTIL@
@@ -274,8 +272,6 @@ GDKX11 = @GDKX11@
 GETTEXT_MACRO_VERSION = @GETTEXT_MACRO_VERSION@
 GLIB_CFLAGS = @GLIB_CFLAGS@
 GLIB_LIBS = @GLIB_LIBS@
-GMODULE_CFLAGS = @GMODULE_CFLAGS@
-GMODULE_LIBS = @GMODULE_LIBS@
 GMSGFMT = @GMSGFMT@
 GMSGFMT_015 = @GMSGFMT_015@
 GREP = @GREP@
@@ -439,18 +435,19 @@ JITTEST_PROG = $(if $(VALGRIND), valgrind $(VALGRIND_ARGS),) $(if $(SGEN),$(top_
 TEST_PROG_RUN = MONO_CFG_DIR=$(mono_build_root)/runtime/etc $(LIBTOOL) --mode=execute $(TEST_PROG)
 JITTEST_PROG_RUN = MONO_CFG_DIR=$(mono_build_root)/runtime/etc $(LIBTOOL) --mode=execute $(JITTEST_PROG)
 RUNTIME_ARGS = --config tests-config --optimize=all --debug
-with_mono_path = MONO_PATH=$(mcs_topdir)/class/lib/net_4_5
+CLASS = $(mcs_topdir)/class/lib/$(DEFAULT_PROFILE)
+with_mono_path = MONO_PATH=$(CLASS)
 RUNTIME = $(with_mono_path) $(top_builddir)/runtime/mono-wrapper
 MKBUNDLE = \
 	PKG_CONFIG_PATH=$(top_builddir):$(PKG_CONFIG_PATH) \
-	$(RUNTIME) $(mcs_topdir)/class/lib/net_4_5/mkbundle.exe
+	$(RUNTIME) $(CLASS)/mkbundle.exe
 
 MCS = $(RUNTIME) $(mcs_topdir)/class/lib/build/mcs.exe -unsafe -debug \
 	-nowarn:0162 -nowarn:0168 -nowarn:0219 -nowarn:0414 -nowarn:0618 \
 	-nowarn:0169 -nowarn:1690 -nowarn:0649 -nowarn:0612 -nowarn:3021 \
 	-nowarn:0197
 
-ILASM = $(RUNTIME) $(mcs_topdir)/class/lib/net_4_5/ilasm.exe
+ILASM = $(RUNTIME) $(CLASS)/ilasm.exe
 BENCHSRC = fib.cs random.cs nested-loops.cs ackermann.cs tight-loop.cs sieve.cs
 STRESS_TESTS_SRC = \
 	abort-stress-1.cs	\
@@ -559,6 +556,7 @@ BASE_TEST_CS_SRC = \
 	many-locals.cs		\
 	string-compare.cs	\
 	test-prime.cs		\
+	test-tls.cs		\
 	params.cs		\
 	reflection.cs		\
 	interface.cs		\
@@ -749,6 +747,7 @@ BASE_TEST_CS_SRC = \
 	bug-80392.2.cs		\
 	dynamic-method-access.2.cs	\
 	dynamic-method-finalize.2.cs	\
+	dynamic-method-stack-traces.cs	\
 	bug-82194.2.cs	\
 	anonarray.2.cs	\
 	ienumerator-interfaces.2.cs	\
@@ -775,6 +774,7 @@ BASE_TEST_CS_SRC = \
 	bug-324535.cs	\
 	modules.cs	\
 	bug-81673.cs	\
+	bug-36848.cs    \
 	bug-81691.cs	\
 	bug-80307.cs	\
 	bug-415577.cs	\
@@ -833,7 +833,12 @@ BASE_TEST_CS_SRC = \
 	sleep.cs \
 	bug-27147.cs	\
 	bug-30085.cs	\
-	bug-17537.cs
+	bug-17537.cs	\
+	pinvoke_ppcc.cs	\
+	pinvoke_ppcs.cs	\
+	pinvoke_ppci.cs	\
+	pinvoke_ppcf.cs	\
+	pinvoke_ppcd.cs
 
 TEST_CS_SRC_DIST = \
 	$(BASE_TEST_CS_SRC)	\
@@ -925,10 +930,9 @@ TEST_CS_SRC_GEN = \
 @NACL_CODEGEN_TRUE@	gsharing-valuetype-layout.exe \
 @NACL_CODEGEN_TRUE@	$(am__append_2)
 
-# These tests hang
+# FIXME: These tests hang/fail for unknown reasons
 @POWERPC64_TRUE@PLATFORM_DISABLED_TESTS = monitor.exe \
-@POWERPC64_TRUE@	finalizer-abort.exe finalizer-exception.exe \
-@POWERPC64_TRUE@	finalizer-exit.exe $(am__append_2)
+@POWERPC64_TRUE@	threadpool-exceptions5.exe $(am__append_2)
 
 # bug #71274
 @POWERPC_TRUE@PLATFORM_DISABLED_TESTS = finalizer-abort.exe \
@@ -977,6 +981,7 @@ TEST_IL_SRC = \
 	cpblkTest.il		\
 	vbinterface.il		\
 	calliTest.il		\
+	calliGenericTest.il		\
 	ckfiniteTest.il		\
 	fault-handler.il		\
 	locallocTest.il		\
@@ -1075,13 +1080,14 @@ EXTRA_DIST = test-driver test-runner.cs $(TEST_CS_SRC_DIST) \
 	unhandled-exception-legacy-configuration.config \
 	appdomain-unload.exe.config unhandled-exception-test-case.2.cs \
 	unhandled-exception-test-runner.2.cs bug-81673-interface.cs \
-	bug-81691-a.cs bug-81691-b.cs bug-81466-lib.il \
+	bug-36848-a.cs bug-81691-a.cs bug-81691-b.cs bug-81466-lib.il \
 	bug-324535-il.il custom-modifiers.2.cs custom-modifiers-lib.il \
 	bug-382986-lib.cs bug-17537-helper.cs coreclr-security.cs \
 	generic-unboxing.2.il generic-boxing.2.il generic-unbox.2.cs \
 	generic-box.2.cs generic-delegate2.2.cs \
 	generic-delegate2-lib.2.il async-exceptions.cs modules.cs \
-	modules-m1.cs $(am__append_3)
+	modules-m1.cs $(am__append_3) appdomain-loader.cs \
+	appdomain-tester.cs
 
 #
 # Test that no symbols are missed in eglib-remap.h
@@ -1096,6 +1102,7 @@ SGEN_TESTS = \
 	sgen-descriptors.exe	\
 	sgen-gshared-vtype.exe	\
 	sgen-domain-unload.exe	\
+	sgen-domain-unload-2.exe	\
 	sgen-weakref-stress.exe	\
 	sgen-cementing-stress.exe	\
 	sgen-case-23400.exe	\
@@ -1162,7 +1169,7 @@ OOM_TESTS = \
 	gc-oom-handling2.exe
 
 noinst_LTLIBRARIES = libtest.la
-AM_CPPFLAGS = $(GLIB_CFLAGS) $(GMODULE_CFLAGS)
+AM_CPPFLAGS = $(GLIB_CFLAGS)
 
 # gcc-3.4.4 emits incorrect code when making indirect calls to stdcall functions using a tail call
 # This shows up when compiling mono_test_marshal_delegate ()
@@ -1550,9 +1557,12 @@ uninstall-am:
 	uninstall-am
 
 
-check-local: assemblyresolve/test/asm.dll testjit test-generic-sharing test-type-load test-cattr-type-load test-reflection-load-with-context test_platform test-process-exit test-messages test-unhandled-exception-2 rm-empty-logs
+check-local: assemblyresolve/test/asm.dll testjit test-generic-sharing test-type-load test-cattr-type-load test-reflection-load-with-context test_platform test-process-exit test-messages test-env-options test-unhandled-exception-2 test-appdomain-unload rm-empty-logs
 check-full: test-sgen check-local
 check-parallel: compile-tests check-full
+
+check-coreclr:
+	$(MAKE) -C $(mono_build_root)/acceptance-tests check-coreclr
 
 # for backwards compatibility on Wrench
 test-wrench: check-parallel
@@ -1592,6 +1602,9 @@ tests: $(TESTSI_CS) $(TESTSI_IL) $(TESTBS) libtest.la $(PREREQSI_IL) $(PREREQSI_
 @HOST_WIN32_FALSE@@NACL_CODEGEN_FALSE@test-messages: w32message.exe
 @HOST_WIN32_FALSE@@NACL_CODEGEN_FALSE@	> test_messages.zero
 @HOST_WIN32_FALSE@@NACL_CODEGEN_FALSE@	$(with_mono_path) $(JITTEST_PROG_RUN) w32message.exe > w32message.allout 2>&1 && cmp test_messages.zero w32message.allout
+
+test-env-options:
+	MONO_ENV_OPTIONS="--version" $(RUNTIME) array-init.exe | grep -q Architecture:
 
 @AMD64_TRUE@test-sgen : sgen-tests
 @AMD64_FALSE@@HOST_WIN32_TRUE@@X86_TRUE@test-sgen :
@@ -1689,7 +1702,11 @@ runtest: $(TESTSI_CS) $(TESTSI_IL) $(TESTBS) libtest.la $(PREREQSI_IL) $(PREREQS
 
 runtest-managed: test-runner.exe $(TESTSI_CS) $(TESTSI_IL) $(TESTBS) libtest.la $(PREREQSI_IL) $(PREREQSI_CS)
 	@if [ "x$$CI" = "x1" ]; then disabled_tests="$(DISABLED_TESTS_WRENCH)"; else disabled_tests="$(DISABLED_TESTS)"; fi; \
-	$(RUNTIME) ./test-runner.exe -j a --disabled "$${disabled_tests}" $(TESTSI_CS) $(TESTBS) $(TESTSI_IL)
+	$(RUNTIME) ./test-runner.exe -j a --testsuite-name "runtime" --disabled "$${disabled_tests}" $(TESTSI_CS) $(TESTBS) $(TESTSI_IL)
+
+runtest-managed-serial: test-runner.exe $(TESTSI_CS) $(TESTSI_IL) $(TESTBS) libtest.la $(PREREQSI_IL) $(PREREQSI_CS)
+	@if [ "x$$CI" = "x1" ]; then disabled_tests="$(DISABLED_TESTS_WRENCH)"; else disabled_tests="$(DISABLED_TESTS)"; fi; \
+	$(RUNTIME) ./test-runner.exe -j 1 --testsuite-name "runtime" --disabled "$${disabled_tests}" $(TESTSI_CS) $(TESTBS) $(TESTSI_IL)
 
 testjit:
 	@if test x$(M) != x0; then $(MAKE) runtest-managed; else $(MAKE) runtest; fi
@@ -1875,7 +1892,7 @@ test-aot:
 	@failed=0; \
 	passed=0; \
 	failed_tests="";\
-	profile=net_4_5;	\
+	profile=$(DEFAULT_PROFILE);	\
 	tmpfile=`mktemp -t mono_aot_output` || exit 1;	\
 	rm -f test-aot-$${name}.stdout test-aot-$${name}.stderr; \
 	for assembly in $(mcs_topdir)/class/lib/$$profile/*.dll	; do	\
@@ -1942,6 +1959,10 @@ bug-81673.exe bug-81673-interface.dll: $(srcdir)/bug-81673.cs $(srcdir)/bug-8167
 	$(MCS) -target:library -out:bug-81673-interface.dll $(srcdir)/bug-81673-interface.cs
 	$(MCS) -out:bug-81673.exe -r:bug-81673-interface.dll $(srcdir)/bug-81673.cs
 	$(MCS) -define:WITH_STOP -target:library -out:bug-81673-interface.dll $(srcdir)/bug-81673-interface.cs
+bug-36848.exe bug-36848-a.dll: $(srcdir)/bug-36848.cs $(srcdir)/bug-36848-a.cs
+	$(MCS) -target:library -out:bug-36848-a.dll $(srcdir)/bug-36848-a.cs
+	$(MCS) -r:bug-36848-a.dll -out:bug-36848.exe $(srcdir)/bug-36848.cs
+	$(MCS) -target:library -out:bug-36848-a.dll $(srcdir)/bug-36848-a.cs /define:WITH_STOP
 bug-81691.exe bug-81691-b.dll: $(srcdir)/bug-81691.cs $(srcdir)/bug-81691-a.cs $(srcdir)/bug-81691-b.cs
 	$(MCS) -target:library -out:bug-81691-a.dll $(srcdir)/bug-81691-a.cs
 	$(MCS) -target:library -out:bug-81691-b.dll -r:bug-81691-a.dll $(srcdir)/bug-81691-b.cs
@@ -2009,7 +2030,7 @@ test-generic-sharing-normal: $(GSHARED_TESTS)
 	done
 
 test-generic-sharing-managed: test-runner.exe $(GSHARED_TESTS)
-	@$(RUNTIME) ./test-runner.exe -j a --opt-sets "gshared gshared,shared gshared,-inline gshared,-inline,shared" $(GSHARED_TESTS)
+	@$(RUNTIME) ./test-runner.exe -j a --testsuite-name "gshared" --opt-sets "gshared gshared,shared gshared,-inline gshared,-inline,shared" $(GSHARED_TESTS)
 
 @NACL_CODEGEN_TRUE@test-generic-sharing:
 @NACL_CODEGEN_FALSE@test-generic-sharing:
@@ -2046,15 +2067,33 @@ test-oom: $(OOM_TESTS)
 	done
 
 @HOST_WIN32_TRUE@test-unhandled-exception-2:
-@HOST_WIN32_FALSE@test-unhandled-exception-2: unhandled-exception.exe
-@HOST_WIN32_FALSE@	@echo "Testing unhandled-exception_1 ..."; $(RUNTIME) $+ 1 1> unhandled-exception_1.exe.stdout 2> unhandled-exception_1.exe.stderr; if test "x$$?" != "x1";   then exit 1; fi;	\
-@HOST_WIN32_FALSE@	 echo "Testing unhandled-exception_2 ..."; $(RUNTIME) $+ 2 1> unhandled-exception_2.exe.stdout 2> unhandled-exception_2.exe.stderr; if test "x$$?" != "x0";   then exit 2; fi;	\
-@HOST_WIN32_FALSE@	 echo "Testing unhandled-exception_3 ..."; $(RUNTIME) $+ 3 1> unhandled-exception_3.exe.stdout 2> unhandled-exception_3.exe.stderr; if test "x$$?" != "x0";   then exit 3; fi;	\
-@HOST_WIN32_FALSE@	 echo "Testing unhandled-exception_4 ..."; $(RUNTIME) $+ 4 1> unhandled-exception_4.exe.stdout 2> unhandled-exception_4.exe.stderr; if test "x$$?" != "x0";   then exit 4; fi;	\
-@HOST_WIN32_FALSE@	 echo "Testing unhandled-exception_5 ..."; $(RUNTIME) $+ 5 1> unhandled-exception_5.exe.stdout 2> unhandled-exception_5.exe.stderr; if test "x$$?" != "x255"; then exit 5; fi;	\
-@HOST_WIN32_FALSE@	 echo "Testing unhandled-exception_6 ..."; $(RUNTIME) $+ 6 1> unhandled-exception_6.exe.stdout 2> unhandled-exception_6.exe.stderr; if test "x$$?" != "x0";   then exit 6; fi;	\
-@HOST_WIN32_FALSE@	 echo "Testing unhandled-exception_7 ..."; $(RUNTIME) $+ 7 1> unhandled-exception_7.exe.stdout 2> unhandled-exception_7.exe.stderr; if test "x$$?" != "x0";   then exit 7; fi;	\
-@HOST_WIN32_FALSE@	 echo "Testing unhandled-exception_8 ..."; $(RUNTIME) $+ 8 1> unhandled-exception_8.exe.stdout 2> unhandled-exception_8.exe.stderr; if test "x$$?" != "x3";   then exit 8; fi
+@HOST_WIN32_FALSE@test-unhandled-exception-2: test-unhandled-exception-2-1 test-unhandled-exception-2-2 test-unhandled-exception-2-3 test-unhandled-exception-2-4	\
+@HOST_WIN32_FALSE@		 test-unhandled-exception-2-5 test-unhandled-exception-2-6 test-unhandled-exception-2-7 test-unhandled-exception-2-8
+
+@HOST_WIN32_FALSE@test-unhandled-exception-2-1: unhandled-exception-1.exe test-runner.exe
+@HOST_WIN32_FALSE@	@$(RUNTIME) ./test-runner.exe --testsuite-name $@ --expected-exit-code 1 $<
+@HOST_WIN32_FALSE@test-unhandled-exception-2-2: unhandled-exception-2.exe test-runner.exe
+@HOST_WIN32_FALSE@	@$(RUNTIME) ./test-runner.exe --testsuite-name $@ --expected-exit-code 0 $<
+@HOST_WIN32_FALSE@test-unhandled-exception-2-3: unhandled-exception-3.exe test-runner.exe
+@HOST_WIN32_FALSE@	@$(RUNTIME) ./test-runner.exe --testsuite-name $@ --expected-exit-code 255 $<
+@HOST_WIN32_FALSE@test-unhandled-exception-2-4: unhandled-exception-4.exe test-runner.exe
+@HOST_WIN32_FALSE@	@$(RUNTIME) ./test-runner.exe --testsuite-name $@ --expected-exit-code 0 $<
+@HOST_WIN32_FALSE@test-unhandled-exception-2-5: unhandled-exception-5.exe test-runner.exe
+@HOST_WIN32_FALSE@	@$(RUNTIME) ./test-runner.exe --testsuite-name $@ --expected-exit-code 255 $<
+@HOST_WIN32_FALSE@test-unhandled-exception-2-6: unhandled-exception-6.exe test-runner.exe
+@HOST_WIN32_FALSE@	@$(RUNTIME) ./test-runner.exe --testsuite-name $@ --expected-exit-code 255 $<
+@HOST_WIN32_FALSE@test-unhandled-exception-2-7: unhandled-exception-7.exe test-runner.exe
+@HOST_WIN32_FALSE@	@$(RUNTIME) ./test-runner.exe --testsuite-name $@ --expected-exit-code 255 $<
+@HOST_WIN32_FALSE@test-unhandled-exception-2-8: unhandled-exception-8.exe test-runner.exe
+@HOST_WIN32_FALSE@	@$(RUNTIME) ./test-runner.exe --testsuite-name $@ --expected-exit-code 3 $<
+test-appdomain-unload: appdomain-loader.exe appdomain-tester.exe
+	$(RUNTIME) -O=gshared appdomain-loader.exe > appdomain-loader.exe.1.stdout || exit 1;
+	$(RUNTIME) appdomain-loader.exe > appdomain-loader.exe.2.stdout || exit 1;
+	MONO_DEBUG_ASSEMBLY_UNLOAD=1 $(RUNTIME) -O=gshared appdomain-loader.exe > appdomain-loader.exe.3.stdout || exit 1;
+	MONO_DEBUG_ASSEMBLY_UNLOAD=1 $(RUNTIME) appdomain-loader.exe > appdomain-loader.exe.4.stdout || exit 1;
+
+coreclr-gcstress:
+	$(MAKE) -C $(mono_build_root)/acceptance-tests coreclr-gcstress
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
